USE [master]
GO

/****** Object:  Database [ADP_Parking]    Script Date: 14/06/2019 08:03:34 PM ******/
CREATE DATABASE [ADP_Parking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ADP_Parking', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ADP_Parking.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ADP_Parking_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ADP_Parking_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [ADP_Parking] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ADP_Parking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ADP_Parking] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ADP_Parking] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ADP_Parking] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ADP_Parking] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ADP_Parking] SET ARITHABORT OFF 
GO

ALTER DATABASE [ADP_Parking] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ADP_Parking] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ADP_Parking] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ADP_Parking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ADP_Parking] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ADP_Parking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ADP_Parking] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ADP_Parking] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ADP_Parking] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ADP_Parking] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ADP_Parking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ADP_Parking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ADP_Parking] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ADP_Parking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ADP_Parking] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ADP_Parking] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ADP_Parking] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ADP_Parking] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ADP_Parking] SET  MULTI_USER 
GO

ALTER DATABASE [ADP_Parking] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ADP_Parking] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ADP_Parking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ADP_Parking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ADP_Parking] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ADP_Parking] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ADP_Parking] SET  READ_WRITE 
GO

